// Code generated by mockery v2.21.1. DO NOT EDIT.

package ohlc

import (
	context "context"

	model "github.com/ctopher7/gltc/v2/part1/model"
	mock "github.com/stretchr/testify/mock"
)

// MockUsecase is an autogenerated mock type for the Usecase type
type MockUsecase struct {
	mock.Mock
}

// GetSummary provides a mock function with given fields: ctx, req
func (_m *MockUsecase) GetSummary(ctx context.Context, req model.GetSummaryReq) (model.Ohlc, error) {
	ret := _m.Called(ctx, req)

	var r0 model.Ohlc
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.GetSummaryReq) (model.Ohlc, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.GetSummaryReq) model.Ohlc); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(model.Ohlc)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.GetSummaryReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessOhlc provides a mock function with given fields: ctx, req
func (_m *MockUsecase) ProcessOhlc(ctx context.Context, req model.ProcessOhlc) error {
	ret := _m.Called(ctx, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ProcessOhlc) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockUsecase creates a new instance of MockUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockUsecase(t mockConstructorTestingTNewMockUsecase) *MockUsecase {
	mock := &MockUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
